# Gowin CLI Synthesis Script for Tang Primer 25K SPI Flash Emulator
# Usage: gw_sh build.tcl

# Device: GW5A-LV25MG121NC1/I0 (Tang Primer 25K, MBGA121N package)
# GW5A-25B variant includes BSRAM
set_device -name GW5A-25B GW5A-LV25MG121NC1/I0

# Select FT245 bus timing profile.
#   FT245_TIMING=pico    - conservative strobes for the RP2040 bridge (default)
#   FT245_TIMING=ft2232h - shorter strobes for a real FT2232H async FIFO
if {[info exists ::env(FT245_TIMING)]} {
    set ft245_timing [string tolower $::env(FT245_TIMING)]
} else {
    set ft245_timing "pico"
}
if {$ft245_timing ne "pico" && $ft245_timing ne "ft2232h"} {
    error "Invalid FT245_TIMING='$ft245_timing' (expected pico or ft2232h)"
}
file mkdir impl/generated
set ft245_cfg [open "impl/generated/ft245_timing.vh" w]
puts $ft245_cfg "// Auto-generated by build.tcl; do not edit."
puts $ft245_cfg "// FT245_TIMING=$ft245_timing"
if {$ft245_timing eq "ft2232h"} {
    puts $ft245_cfg "`define FT245_TIMING_FT2232H 1"
} else {
    puts $ft245_cfg "`define FT245_TIMING_PICO 1"
}
close $ft245_cfg
puts "FT245 timing profile: $ft245_timing"

# Add Verilog source files
add_file src/top.v
add_file src/spi_trx.v
add_file src/sdram.v
add_file src/glue.v
add_file src/uart.v
add_file src/ft245.v
add_file src/fifo.v
add_file src/logger.v
add_file src/util.v
add_file src/pll.v

# Add constraints
add_file tangprimer25k.cst
add_file tangprimer25k.sdc

# Set top module
set_option -top_module top

# Synthesis options
set_option -verilog_std v2001
set_option -use_sspi_as_gpio 1
set_option -use_mspi_as_gpio 1
set_option -use_ready_as_gpio 1
set_option -use_done_as_gpio 1
set_option -use_i2c_as_gpio 1
set_option -use_cpu_as_gpio 1
set_option -print_all_synthesis_warning 1

# Place and route options
set_option -place_option 1
set_option -route_option 1

# Output directory
set_option -output_base_name spi_flash

# Run synthesis
run syn

# Run place and route
run pnr
